#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 13 17:05:24 2019

@author: jay
"""

from keras.models import Sequential #classifier
from keras.layers import Conv2D #convolution
from keras.layers import MaxPooling2D #pooling
from keras.layers import Flatten #flattening the pooled features to a long feature vector
from keras.layers import Dense #for hidden layers

def build_classifier_gridsearchCV(optimizer):